// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package certificate

// Injectors from injector.go:

func InitializedCertService() (*CertificateService, error) {
	certificateRepository := NewCertificateRepository()
	certificateService, err := NewCertificateService(certificateRepository)
	if err != nil {
		return nil, err
	}
	return certificateService, nil
}
