openapi: '3.0.3'
info:
  title: Go-Language RESTful API
  version: '1.0'
# servers:
#   - url: http:://localhost:5000
servers: [
  { 
    url: http:://localhost:5000
  }
]
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
